Revert "Settings: per-app cellular data and wifi restrictions"
This reverts commit 5d6d55212f5b7a5d84eec88c78ebcda29ce93443.

- FC occurs. Requires a fix.

Logcat:
05-06 21:46:08.106 17750 17750 D AndroidRuntime: Shutting down VM
05-06 21:46:08.107 17750 17750 E AndroidRuntime: FATAL EXCEPTION: main
05-06 21:46:08.107 17750 17750 E AndroidRuntime: Process:
com.android.settings, PID: 17750
05-06 21:46:08.107 17750 17750 E AndroidRuntime:
java.lang.IllegalArgumentException: command '935 bandwidth
addrestrictappsondata rmnet_data0 10021' failed with '500 935 Unknown
bandwidth cmd'
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.os.Parcel.readException(Parcel.java:2008)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.os.Parcel.readException(Parcel.java:1950)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.net.INetworkPolicyManager$Stub$Proxy.addUidPolicy(INetworkPolicyManager.java:331)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.net.NetworkPolicyManager.addUidPolicy(NetworkPolicyManager.java:159)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
com.android.settings.datausage.AppDataUsage.setAppRestriction(AppDataUsage.java:388)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
com.android.settings.datausage.AppDataUsage.setAppRestrictAllData(AppDataUsage.java:378)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
com.android.settings.datausage.AppDataUsage.onPreferenceChange(AppDataUsage.java:264)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.support.v7.preference.Preference.callChangeListener(Preference.java:1053)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.support.v7.preference.TwoStatePreference.onClick(TwoStatePreference.java:66)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.support.v7.preference.Preference.performClick(Preference.java:1115)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.support.v7.preference.Preference.performClick(Preference.java:1100)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.support.v14.preference.SwitchPreference.performClick(SwitchPreference.java:212)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.support.v7.preference.Preference$1.onClick(Preference.java:170)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.view.View.performClick(View.java:6294)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.view.View$PerformClick.run(View.java:24770)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.os.Handler.handleCallback(Handler.java:790)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.os.Handler.dispatchMessage(Handler.java:99)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.os.Looper.loop(Looper.java:164)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
android.app.ActivityThread.main(ActivityThread.java:6524)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
java.lang.reflect.Method.invoke(Native Method)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:460)
05-06 21:46:08.107 17750 17750 E AndroidRuntime: 	at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-06 21:46:08.114   929  5251 W ActivityManager:   Force finishing
activity com.android.settings/.SubSettings

Signed-off-by: spezi77 <spezi7713@gmx.net>